export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_RESET = 'CREATE_TASK_RESET';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

export const LIST_TASKS = 'LIST_TASKS';
export const LIST_TASKS_FAILURE = 'LIST_TASKS_FAILURE';
export const LIST_TASKS_SUCCESS = 'LIST_TASKS_SUCCESS';

export const DETAIL_TASK = 'DETAIL_TASK';
export const DETAIL_TASK_RESET = 'DETAIL_TASK_RESET';
export const DETAIL_TASK_FAILURE = 'DETAIL_TASK_FAILURE';
export const DETAIL_TASK_SUCCESS = 'DETAIL_TASK_SUCCESS';

export const EDIT_TASK = 'EDIT_TASK';
export const EDIT_TASK_RESET = 'EDIT_TASK_RESET';
export const EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';

export const SET_TASK_DEFAULTS = 'SET_TASK_DEFAULTS';